# Path to oh-my-zsh installation
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="robbyrussell"

# Plugins
plugins=(git docker python node npm aws)

# Source oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Aliases
alias ll='ls -la'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'

# Environment
export PATH=$HOME/.local/bin:$PATH
export EDITOR=vim

# Welcome message
echo "Ready! Your data directory is at: /home/user/data"
